### ISSUE TITLE
Google "Messages"

### ISSUE THREAD

**Issue by skug67** [EionRobb/purple-hangouts#218]
With Hangouts apparently being phased out and Google's new "Messages" platform including a web interface, is there any chance of building a libpurple connection to the new platform that would allow at least partial interoperability with XMPP?  (I have no idea what's going on under the hood and realize that this may be a complete technical non-starter or even if theoretically possible such a heavy lift that nobody is interested in trying. But I figured it couldn't hurt to ask....)

**Comment by EionRobb** [comment]
Hangouts is supposedly being phased out in favour of Hangouts Chat, a totally different system with a similar-sounding name. 

I have been looking at the Messages relay system (since RCS messaging is very tempting) but trying to extract/reverse the Protobufs out of the app/website has been difficult

Probably a bit outside the scope of this particular plugin :)
